### PR TITLE
new node

### PR DESCRIPTION
**Pull request by mycoconut**
it's  my bp json

### CODE REVIEW

**Comment by eosforce** [comment]
Your node seemingly is not syncing now, please check it out.

**Comment by mycoconut** [comment]
Already started, please re-review

**Comment by eosforce** [comment]
```bash
$ curl http://47.75.183.254:8888/v1/chain/get_info
{"server_version":"025ffad3","head_block_num":0,"last_irreversible_block_num":0,"head_block_id":"0000000000000000000000000000000000000000000000000000000000000000","head_block_time":"2018-03-01T12:00:00","head_block_producer":""}
```

Your node did have started, but it failed to sync the network.

**Comment by mycoconut** [comment]
{"server_version":"025ffad3","head_block_num":671061,"last_irreversible_block_num":670899,"head_block_id":"000a3d55eac42dc3bbb7316c9524875919f5803ac1580065ae50abc82716233d","head_block_time":"2018-05-07T23:56:41","head_block_producer":"eosantpool"}

It's  ok

**Comment by eosforce** [comment]
Your PR has lots of unrelated changes. Only add a json file under bp directory for your application. Please refer to any other merged PR.

**Pull request closed without merging**
